################## build ###############################
FROM node:lts-bullseye AS build

### set working directory
WORKDIR /app

### copy source code
COPY public ./public
COPY node_modules ./node_modules
COPY src ./src

### add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

### install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY tsconfig.json ./
COPY .env.production ./.env.production

RUN npm install --silent

# replace config file with production version
# add_production_configs
#

RUN npm run build

#################### nginx #############################
FROM nginx:stable-alpine-slim AS production
# FROM nginx:stable AS production

### get react build files
RUN rm -r /usr/share/nginx/html
COPY --from=build /app/build /usr/share/nginx/html

### replace nginx files
COPY nginx.conf /etc/nginx/conf.d/default.conf

# ### run
# CMD ["nginx", "-g", "daemon off;"]