FROM node:20 AS build

# Set working directory
WORKDIR /app
# Copy package files
COPY package.json package-lock.json ./  

# Install dependencies  
RUN npm install --silent
COPY . .
RUN npm run build --silent  
FROM node:20 AS production

# Set working directory
WORKDIR /app

# Copy the build output and necessary files from the build stage
COPY --from=build /app/public ./public
COPY --from=build /app/build ./build
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/node_modules /app/node_modules
EXPOSE 3000
CMD ["npx", "remix-serve", "build/server/index.js"]
