FROM node:lts-bullseye

### set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* yarn.lock* ./  
RUN npm install --silent

### copy source code
COPY public ./public
# COPY node_modules ./node_modules
COPY app ./app
COPY tsconfig.json pdfjs.d.ts postcss.config.js tailwind.config.ts tsconfig.json tsconfig.tsbuildinfo vite.config.ts ./

EXPOSE 3000
# CMD ["npm", "run", "dev"]
# CMD ["/bin/bash"]