server {
  listen 8000;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    add_header Cache-Control "no-cache, no-store, must-revalidate";
    add_header Pragma "no-cache";
    add_header Expires 0;
    try_files $uri $uri/ /index.html;
  }

  location /favicon.ico {
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET';
    add_header 'Access-Control-Allow-Headers' 'Content-Type';
    add_header Cache-Control "max-age=86400";
  }
}